language: python

before_install:
    - find /usr/lib -type f -iname libssl*.*
    - sudo add-apt-repository -y ppa:scilifelab/scilifelab
    - sudo apt-get install -y build-essential zlib1g-dev zlib1g libgomp1 bowtie
    - gcc -v
    - lsb_release -a
python:
    - "2.7"
script:
    - make python
    - cd tests && nosetests -v -s -P --with-timer -a standard
notifications:
    email: false
